import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const SITE_NAME = process.env.SITE_NAME ?? "SEO Prompt AI";

/** Sanitize for use in filename: replace spaces with hyphens, remove invalid chars. */
function sanitizeFilenamePart(s: string): string {
  return s
    .trim()
    .replace(/\s+/g, "-")
    .replace(/[<>:"/\\|?*]/g, "")
    .slice(0, 80) || "prompt";
}

/**
 * Build a PDF with the SEO prompt content, branded with user name and brand name.
 * Returns the PDF buffer and a suggested filename: {userName}-{brandName}-seo-prompt.pdf
 */
export async function buildPromptPdf(
  prompt: string,
  userName: string,
  brandName: string
): Promise<{ buffer: Buffer; filename: string }> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 50;
  const lineHeight = 14;
  const fontSize = 10;
  const titleSize = 12;

  let page = doc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  // Header: title with user + brand
  const title = `${userName || "SEO"} — ${brandName || "Project"} — SEO Prompt`;
  page.drawText(title, {
    x: margin,
    y,
    size: titleSize,
    font: boldFont,
    color: rgb(0.1, 0.15, 0.35),
  });
  y -= lineHeight * 1.5;

  page.drawText(`Generated by ${SITE_NAME}`, {
    x: margin,
    y,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });
  y -= lineHeight * 2;

  // Prompt content (split into lines that fit width)
  const maxCharsPerLine = Math.floor((pageWidth - margin * 2) / (fontSize * 0.6));
  const wrap = (s: string) => {
    const out: string[] = [];
    for (const line of s.split("\n")) {
      let remaining = line;
      while (remaining.length > maxCharsPerLine) {
        const chunk = remaining.slice(0, maxCharsPerLine);
        const lastSpace = chunk.lastIndexOf(" ");
        const breakAt = lastSpace > maxCharsPerLine * 0.5 ? lastSpace : maxCharsPerLine;
        out.push(remaining.slice(0, breakAt).trim());
        remaining = remaining.slice(breakAt).trim();
      }
      if (remaining) out.push(remaining);
    }
    return out;
  };
  const wrapped = wrap(prompt);
  for (const line of wrapped) {
    if (y < margin + lineHeight) {
      page = doc.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }
    page.drawText(line, {
      x: margin,
      y,
      size: fontSize,
      font,
      color: rgb(0.15, 0.15, 0.15),
    });
    y -= lineHeight;
  }

  const pdfBytes = await doc.save();
  const userPart = sanitizeFilenamePart(userName || "user");
  const brandPart = sanitizeFilenamePart(brandName || "brand");
  const filename = `${userPart}-${brandPart}-seo-prompt.pdf`;

  return { buffer: Buffer.from(pdfBytes), filename };
}
